<?php
require '../../config/db.php';
require '../../includes/asset_helpers.php';
require '../../vendor/autoload.php'; // adjust path if your vendor folder is elsewhere
require_role(['Admin']);

use Mpdf\Mpdf;

$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT); // assets.id
if (!$id) { header('Location: index.php?success=Invalid asset selected.'); exit; }

// Bring the asset's value up to date before printing it.
asset_run_depreciation_catchup($conn, $id);

$assetStmt = mysqli_prepare($conn, 'SELECT assets.*, departments.name AS department_name,
        users.names AS created_by_name, users.role AS created_by_role, users.phone AS created_by_phone,
        roles.name AS created_by_position
    FROM assets
    LEFT JOIN departments ON assets.responsible_department_id = departments.id
    LEFT JOIN users ON assets.created_by = users.id
    LEFT JOIN roles ON users.role_id = roles.id
    WHERE assets.id = ?');
mysqli_stmt_bind_param($assetStmt, 'i', $id);
mysqli_stmt_execute($assetStmt);
$asset = mysqli_fetch_assoc(mysqli_stmt_get_result($assetStmt));
if (!$asset) { header('Location: index.php?success=Asset not found.'); exit; }

$historyStmt = mysqli_prepare($conn, 'SELECT valuation_date, daily_depreciation, value FROM asset_valuation_history WHERE asset_id = ? ORDER BY valuation_date ASC');
mysqli_stmt_bind_param($historyStmt, 'i', $id);
mysqli_stmt_execute($historyStmt);
$historyResult = mysqli_stmt_get_result($historyStmt);

function money($v) { return number_format((float) $v, 2); }
$h = function ($v) { return htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); };

$docTitle = 'Asset Depreciation Report';

$statusBadge = [
    'Active' => ['#0FA968', '#E1F7EE'],
    'Under Maintenance' => ['#E68A1C', '#FDF1DF'],
    'Disposed' => ['#8A90A3', '#F1F3F9'],
    'Lost' => ['#E24B4A', '#FCEAEA'],
];
$badge = $statusBadge[$asset['status']] ?? ['#8A90A3', '#F1F3F9'];

$usefulLifeYears = round(((int) $asset['useful_life_days']) / 365, 2);
$dailyAmount = asset_daily_depreciation_amount((float) $asset['acquisition_value'], (float) $asset['residual_value'], (int) $asset['useful_life_days']);
$depreciatedSoFar = round((float) $asset['acquisition_value'] - (float) $asset['current_value'], 2);

$logoPath = __DIR__ . '/../../assets/images/rise.jpg';

// ---- Repeating header ----
$headerHtml = '
<table width="100%" style="border-bottom:2px solid #1E2333; padding-bottom:6px;">
  <tr>
    <td style="width:60%; vertical-align:top;">
      <table cellpadding="0" cellspacing="0" width="100%">
       <tr><td><img src="' . $logoPath . '" style="height:70px; width:auto;"></td></tr>
         <tr><td style="padding-top:8px;">
          <span style="font-size:24px; font-weight:900; color:#000000; letter-spacing:0.5px;">RISE MOTIVE</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">TIN Number:122923513</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">Website: www.risemotive.rw</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">Kicukiro District, Kigali, Rwanda</span>
           </td></tr>
      </table>
    </td>
    <td style="width:40%; text-align:right; vertical-align:top;">
      <span style="font-size:14px; font-weight:700; color:#1E2333;">' . $h($docTitle) . '</span><br>
      <span style="font-size:9px; color:#6B7280;">' . $h($asset['asset_code']) . '</span><br>
      <span style="font-size:8px; font-weight:700; color:' . $badge[0] . '; background:' . $badge[1] . '; padding:2px 8px; border-radius:8px;">' . $h(strtoupper($asset['status'])) . '</span>
    </td>
  </tr>
</table>';

// ---- Repeating footer ----
$footerHtml = '
<table width="100%" style="border-top:1px solid #E4E8F2; padding-top:4px;">
  <tr>
    <td style="width:50%; font-size:8px; color:#1E2333;">Generated by RISE MOTIVE &middot; ' . date('d M Y, H:i') . '</td>
    <td style="width:50%; text-align:right; font-size:8px; color:#1E2333;">Page {PAGENO} of {nbpg}</td>
  </tr>
</table>';

// ---- Main body content ----
ob_start();
?>
<style>
  body { font-family: sans-serif; color:#1E2333; font-size:11px; }
  table.info-grid { width:100%; border:1px solid #E4E8F2; border-radius:6px; font-size:10px; margin-bottom:14px; }
  table.info-grid td { padding:5px 10px; }
  table.info-grid .label { color:#6B7280; }
  table.items { width:100%; border-collapse:collapse; font-size:9px; margin-bottom:10px; }
  table.items thead td { font-size:8px; text-transform:uppercase; color:#000000; border-bottom:1px solid #E4E8F2; padding:4px 3px; font-weight:800; }
  table.items tbody td { padding:4px 3px; border-bottom:1px solid #E4E8F2; }
  table.items td.amount { text-align:right; }
  table.totals { width:55%; margin-left:45%; font-size:10px; page-break-inside: avoid; }
  table.totals td { padding:3px 0; }
  table.totals td.val { text-align:right; }
  table.totals tr.grand td { border-top:2px solid #1E2333; font-size:13px; font-weight:800; color:#1E2FE0; padding-top:6px; }
  .sig-block { margin-top:18px; padding-top:10px; border-top:1px solid #E4E8F2; font-size:10px; page-break-inside: avoid; }
  .sig-heading { font-weight:800; font-size:11px; }
  .sig-sub { color:#1E2333; font-weight:600; margin-bottom:6px; }
  .sig-label { color:#1E2333; display:inline-block; width:70px; }
  .footnote { margin-top:12px; font-size:9px; color:#1E2333; }
</style>

<table class="info-grid">
  <tr>
    <td width="50%"><span class="label"><strong>Asset Name:&nbsp;</strong></span><?= $h($asset['asset_name']); ?></td>
    <td width="50%"><span class="label"><strong>Asset Code:&nbsp;</strong></span><?= $h($asset['asset_code']); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Type:&nbsp;</strong></span><?= $h($asset['asset_type']); ?></td>
    <td><span class="label"><strong>Department:&nbsp;</strong></span><?= $h($asset['department_name'] ?? '—'); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Acquisition Date:&nbsp;</strong></span><?= date('d M Y', strtotime($asset['acquisition_date'])); ?></td>
    <td><span class="label"><strong>Acquisition Value:&nbsp;</strong></span>RWF <?= money($asset['acquisition_value']); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Residual Value:&nbsp;</strong></span>RWF <?= money($asset['residual_value']); ?></td>
    <td><span class="label"><strong>Useful Life:&nbsp;</strong></span><?= $usefulLifeYears; ?> years (<?= (int) $asset['useful_life_days']; ?> days)</td>
  </tr>
  <tr>
    <td><span class="label"><strong>Method:&nbsp;</strong></span><?= $h($asset['depreciation_method'] ?? 'Straight-Line'); ?></td>
    <td><span class="label"><strong>Daily Depreciation:&nbsp;</strong></span>RWF <?= money($dailyAmount); ?></td>
  </tr>
</table>

<table class="items">
  <thead>
    <tr>
      <td>Date</td>
      <td class="amount">Daily Depreciation (RWF)</td>
      <td class="amount">Value (RWF)</td>
    </tr>
  </thead>
  <tbody>
    <?php while ($row = mysqli_fetch_assoc($historyResult)) { ?>
    <tr>
      <td><?= date('d M Y', strtotime($row['valuation_date'])); ?></td>
      <td class="amount"><?= money($row['daily_depreciation']); ?></td>
      <td class="amount"><?= money($row['value']); ?></td>
    </tr>
    <?php } ?>
  </tbody>
</table>

<table class="totals">
  <tr><td>Depreciated So Far</td><td class="val">RWF <?= money($depreciatedSoFar); ?></td></tr>
  <tr class="grand"><td>Current Value</td><td class="val">RWF <?= money($asset['current_value']); ?></td></tr>
</table>

<div class="sig-block">
  <div class="sig-heading"><strong>For RISE MOTIVE</strong></div>
  <div class="sig-sub">Asset Registered By:</div>
  <div><span class="sig-label">Name:</span> <strong><?= $h($asset['created_by_name'] ?? '—'); ?></strong></div>
  <div><span class="sig-label">Position:</span> <strong><?= $h($asset['created_by_position'] ?? ucfirst($asset['created_by_role'] ?? '—')); ?></strong></div>
  <div><span class="sig-label">Contact:</span> <strong><?= $h($asset['created_by_phone'] ?? '—'); ?></strong></div>
</div>

<div class="footnote">
  This report shows the value and depreciation history of <?= $h($asset['asset_name']); ?> as at <?= date('d M Y'); ?>. Rise Beyond Limits!
</div>
<?php
$bodyHtml = ob_get_clean();

// ---- Build the PDF ----
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 55,
    'margin_bottom' => 18,
    'margin_header' => 10,
    'margin_footer' => 6,
    'margin_left' => 15,
    'margin_right' => 15,
]);

$mpdf->SetHTMLHeader($headerHtml);
$mpdf->SetHTMLFooter($footerHtml);
$mpdf->WriteHTML($bodyHtml);

$filename = 'Asset-Report-' . preg_replace('/[^A-Za-z0-9\-]/', '', $asset['asset_code']) . '.pdf';

$mpdf->Output($filename, \Mpdf\Output\Destination::INLINE); 