<?php
require '../../config/db.php';
require '../../vendor/autoload.php'; // adjust path if your vendor folder is elsewhere
require_role(['Admin']);

use Mpdf\Mpdf;

$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT); // loan_payments.id
if (!$id) { header('Location: index.php?success=Invalid receipt requested.'); exit; }

$statement = mysqli_prepare($conn, 'SELECT loan_payments.*, loans.lender, loans.loan_type, loans.loan_amount,
        loans.loan_start_date, loans.total_payable,
        users.names AS recorded_by_name, users.role AS recorded_by_role, users.phone AS recorded_by_phone,
        roles.name AS recorded_by_position
    FROM loan_payments
    JOIN loans ON loan_payments.loan_id = loans.id
    LEFT JOIN users ON loan_payments.recorded_by = users.id
    LEFT JOIN roles ON users.role_id = roles.id
    WHERE loan_payments.id = ?');
mysqli_stmt_bind_param($statement, 'i', $id);
mysqli_stmt_execute($statement);
$payment = mysqli_fetch_assoc(mysqli_stmt_get_result($statement));
if (!$payment) { header('Location: index.php?success=Receipt not found.'); exit; }

function money($v) { return number_format((float) $v, 2); }

$docTitle = 'Loan Repayment Receipt';
$docNumber = 'No. RM' . str_pad($payment['id'], 6, '0', STR_PAD_LEFT);
$loanRef = 'LN-' . str_pad($payment['loan_id'], 6, '0', STR_PAD_LEFT);

$logoPath = __DIR__ . '/../../assets/images/rise.jpg';

// ---- Repeating header ----
$headerHtml = '
<table width="100%" style="border-bottom:2px solid #1E2333; padding-bottom:6px;">
  <tr>
    <td style="width:60%; vertical-align:top;">
      <table cellpadding="0" cellspacing="0" width="100%">
       <tr><td><img src="' . $logoPath . '" style="height:70px; width:auto;"></td></tr>
         <tr><td style="padding-top:8px;">
          <span style="font-size:24px; font-weight:900; color:#000000; letter-spacing:0.5px;">RISE MOTIVE</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">TIN Number:122923513</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">Website: www.risemotive.rw</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">Kicukiro District, Kigali, Rwanda</span>
           </td></tr>
      </table>
    </td>
    <td style="width:40%; text-align:right; vertical-align:top;">
      <span style="font-size:14px; font-weight:700; color:#1E2333;">' . htmlspecialchars($docTitle, ENT_QUOTES, 'UTF-8') . '</span><br>
      <span style="font-size:9px; color:#6B7280;">' . htmlspecialchars($docNumber, ENT_QUOTES, 'UTF-8') . '</span><br>
      <span style="font-size:8px; font-weight:700; color:#0FA968; background:#E1F7EE; padding:2px 8px; border-radius:8px;">PAID</span>
    </td>
  </tr>
</table>';

// ---- Repeating footer ----
$footerHtml = '
<table width="100%" style="border-top:1px solid #E4E8F2; padding-top:4px;">
  <tr>
    <td style="width:50%; font-size:8px; color:#1E2333;">Generated by MY MOTIVE &middot; ' . date('d M Y, H:i') . '</td>
    <td style="width:50%; text-align:right; font-size:8px; color:#1E2333;">Page {PAGENO} of {nbpg}</td>
  </tr>
</table>';

// ---- Main body content ----
ob_start();
?>
<style>
  body { font-family: sans-serif; color:#1E2333; font-size:11px; }
  table.info-grid { width:100%; border:1px solid #E4E8F2; border-radius:6px; font-size:10px; margin-bottom:14px; }
  table.info-grid td { padding:5px 10px; }
  table.info-grid .label { color:#6B7280; width:110px; display:inline-block; margin-right:8px; }
  table.items { width:100%; border-collapse:collapse; font-size:10px; margin-bottom:10px; }
  table.items thead td { font-size:9px; text-transform:uppercase; color:#000000; border-bottom:1px solid #E4E8F2; padding:4px 0; font-weight:800; }
  table.items tbody td { padding:6px 0; border-bottom:1px solid #E4E8F2; }
  table.items td.amount { text-align:right; }
  table.totals { width:50%; margin-left:50%; font-size:10px; page-break-inside: avoid; }
  table.totals td { padding:3px 0; }
  table.totals td.val { text-align:right; }
  table.totals tr.grand td { border-top:2px solid #1E2333; font-size:13px; font-weight:800; color:#1E2FE0; padding-top:6px; }
  .sig-block { margin-top:18px; padding-top:10px; border-top:1px solid #E4E8F2; font-size:10px; }
  .sig-heading { font-weight:800; font-size:11px; }
  .sig-sub { color:#1E2333; font-weight:600; margin-bottom:6px; }
  .sig-label { color:#1E2333; display:inline-block; width:70px; }
  .footnote { margin-top:12px; font-size:9px; color:#1E2333; }
</style>

<table class="info-grid">
  <tr>
    <td width="50%"><span class="label"><strong>Lender:&nbsp;</strong></span><?= htmlspecialchars($payment['lender'], ENT_QUOTES, 'UTF-8'); ?></td>
    <td width="50%"><span class="label"><strong>Payment Date:&nbsp;</strong></span><?= date('d M Y', strtotime($payment['payment_date'])); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Loan Type:&nbsp;</strong></span><?= htmlspecialchars($payment['loan_type'], ENT_QUOTES, 'UTF-8'); ?></td>
    <td><span class="label"><strong>Loan Reference:&nbsp;</strong></span><?= htmlspecialchars($loanRef, ENT_QUOTES, 'UTF-8'); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Original Loan:&nbsp;</strong></span>RWF <?= money($payment['loan_amount']); ?></td>
    <td><span class="label"><strong>Recorded By:&nbsp;</strong></span><?= htmlspecialchars($payment['recorded_by_name'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
  </tr>
</table>

<table class="items">
  <thead>
    <tr><td>Description</td><td class="amount">Amount (RWF)</td></tr>
  </thead>
  <tbody>
    <tr>
      <td>Principal Repayment</td>
      <td class="amount"><?= money($payment['principal_portion']); ?></td>
    </tr>
    <tr>
      <td>Interest Repayment</td>
      <td class="amount"><?= money($payment['interest_portion']); ?></td>
    </tr>
  </tbody>
</table>

<table class="totals">
  <tr class="grand"><td>Total Paid</td><td class="val">RWF <?= money($payment['amount']); ?></td></tr>
  <tr><td>Outstanding Balance After Payment</td><td class="val">RWF <?= money($payment['remaining_balance']); ?></td></tr>
</table>

<?php if ($payment['notes']) { ?>
<div style="margin-top:14px; font-size:10px;">
  <strong>Notes:</strong> <?= nl2br(htmlspecialchars($payment['notes'], ENT_QUOTES, 'UTF-8')); ?>
</div>
<?php } ?>

<div class="sig-block">
  <div class="sig-heading"><strong>For RISE MOTIVE</strong></div>
  <div class="sig-sub">Payment Recorded By:</div>
  <div><span class="sig-label">Name:</span> <strong><?= htmlspecialchars($payment['recorded_by_name'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></strong></div>
  <div><span class="sig-label">Position:</span> <strong><?= htmlspecialchars($payment['recorded_by_position'] ?? ucfirst($payment['recorded_by_role'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></strong></div>
  <div><span class="sig-label">Contact:</span> <strong><?= htmlspecialchars($payment['recorded_by_phone'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></strong></div>
</div>

<div class="footnote">
  This receipt confirms a loan repayment made to <?= htmlspecialchars($payment['lender'], ENT_QUOTES, 'UTF-8'); ?>.<br><br>Rise Beyond Limits!
</div>
<?php
$bodyHtml = ob_get_clean();

// ---- Build the PDF ----
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 55,
    'margin_bottom' => 18,
    'margin_header' => 10,
    'margin_footer' => 6,
    'margin_left' => 15,
    'margin_right' => 15,
]);

$mpdf->SetHTMLHeader($headerHtml);
$mpdf->SetHTMLFooter($footerHtml);
$mpdf->WriteHTML($bodyHtml);

$filename = 'Loan-Receipt-RM' . str_pad($payment['id'], 6, '0', STR_PAD_LEFT) . '.pdf';

$mpdf->Output($filename, \Mpdf\Output\Destination::INLINE);