<?php
require '../../config/db.php';
require '../../vendor/autoload.php'; // adjust path if your vendor folder is elsewhere
require_role(['Admin']);

use Mpdf\Mpdf;

$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT); // loans.id
if (!$id) { header('Location: index.php?success=Invalid loan selected.'); exit; }

$loanStmt = mysqli_prepare($conn, 'SELECT loans.*,
        users.names AS created_by_name, users.role AS created_by_role, users.phone AS created_by_phone,
        roles.name AS created_by_position
    FROM loans
    LEFT JOIN users ON loans.created_by = users.id
    LEFT JOIN roles ON users.role_id = roles.id
    WHERE loans.id = ?');
mysqli_stmt_bind_param($loanStmt, 'i', $id);
mysqli_stmt_execute($loanStmt);
$loan = mysqli_fetch_assoc(mysqli_stmt_get_result($loanStmt));
if (!$loan) { header('Location: index.php?success=Loan not found.'); exit; }

$scheduleStmt = mysqli_prepare($conn, 'SELECT * FROM loan_schedule WHERE loan_id = ? ORDER BY installment_no ASC');
mysqli_stmt_bind_param($scheduleStmt, 'i', $id);
mysqli_stmt_execute($scheduleStmt);
$scheduleResult = mysqli_stmt_get_result($scheduleStmt);

function money($v) { return number_format((float) $v, 2); }
$h = function ($v) { return htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); };

$docTitle = 'Loan Repayment Schedule';
$loanRef = 'LN-' . str_pad($loan['id'], 6, '0', STR_PAD_LEFT);

$statusBadge = [
    'Active' => ['#0FA968', '#E1F7EE'],
    'Fully Paid' => ['#1E2FE0', '#E6E8FD'],
    'Defaulted' => ['#E24B4A', '#FCEAEA'],
    'Cancelled' => ['#8A90A3', '#F1F3F9'],
];
$badge = $statusBadge[$loan['status']] ?? ['#8A90A3', '#F1F3F9'];

$logoPath = __DIR__ . '/../../assets/images/rise.jpg';

// ---- Repeating header ----
$headerHtml = '
<table width="100%" style="border-bottom:2px solid #1E2333; padding-bottom:6px;">
  <tr>
    <td style="width:60%; vertical-align:top;">
      <table cellpadding="0" cellspacing="0" width="100%">
       <tr><td><img src="' . $logoPath . '" style="height:70px; width:auto;"></td></tr>
         <tr><td style="padding-top:8px;">
          <span style="font-size:24px; font-weight:900; color:#000000; letter-spacing:0.5px;">RISE MOTIVE</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">TIN Number:122923513</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">Website: www.risemotive.rw</span><br>
           <span style="font-size:10px; font-weight:700; color:#1E2333; margin-top:8px; display:inline-block;">Kicukiro District, Kigali, Rwanda</span>
           </td></tr>
      </table>
    </td>
    <td style="width:40%; text-align:right; vertical-align:top;">
      <span style="font-size:14px; font-weight:700; color:#1E2333;">' . $h($docTitle) . '</span><br>
      <span style="font-size:9px; color:#6B7280;">' . $h($loanRef) . '</span><br>
      <span style="font-size:8px; font-weight:700; color:' . $badge[0] . '; background:' . $badge[1] . '; padding:2px 8px; border-radius:8px;">' . $h(strtoupper($loan['status'])) . '</span>
    </td>
  </tr>
</table>';

// ---- Repeating footer ----
$footerHtml = '
<table width="100%" style="border-top:1px solid #E4E8F2; padding-top:4px;">
  <tr>
    <td style="width:50%; font-size:8px; color:#1E2333;">Generated by RISE MOTIVE &middot; ' . date('d M Y, H:i') . '</td>
    <td style="width:50%; text-align:right; font-size:8px; color:#1E2333;">Page {PAGENO} of {nbpg}</td>
  </tr>
</table>';

// ---- Main body content ----
ob_start();
?>
<style>
  body { font-family: sans-serif; color:#1E2333; font-size:11px; }
  table.info-grid { width:100%; border:1px solid #E4E8F2; border-radius:6px; font-size:10px; margin-bottom:14px; }
  table.info-grid td { padding:5px 10px; }
  table.info-grid .label { color:#6B7280; }
  table.items { width:100%; border-collapse:collapse; font-size:9px; margin-bottom:10px; }
  table.items thead td { font-size:8px; text-transform:uppercase; color:#000000; border-bottom:1px solid #E4E8F2; padding:4px 3px; font-weight:800; }
  table.items tbody td { padding:5px 3px; border-bottom:1px solid #E4E8F2; }
  table.items tfoot td { padding:6px 3px; border-top:2px solid #1E2333; font-weight:800; }
  table.items td.amount { text-align:right; }
  table.totals { width:50%; margin-left:50%; font-size:10px; page-break-inside: avoid; }
  table.totals td { padding:3px 0; }
  table.totals td.val { text-align:right; }
  table.totals tr.grand td { border-top:2px solid #1E2333; font-size:13px; font-weight:800; color:#1E2FE0; padding-top:6px; }
  .sig-block { margin-top:18px; padding-top:10px; border-top:1px solid #E4E8F2; font-size:10px; page-break-inside: avoid; }
  .sig-heading { font-weight:800; font-size:11px; }
  .sig-sub { color:#1E2333; font-weight:600; margin-bottom:6px; }
  .sig-label { color:#1E2333; display:inline-block; width:70px; }
  .footnote { margin-top:12px; font-size:9px; color:#1E2333; }
</style>

<table class="info-grid">
  <tr>
    <td width="50%"><span class="label"><strong>Lender:&nbsp;</strong></span><?= $h($loan['lender']); ?></td>
    <td width="50%"><span class="label"><strong>Loan Reference:&nbsp;</strong></span><?= $h($loanRef); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Lender Type:&nbsp;</strong></span><?= $h($loan['loan_type']); ?></td>
    <td><span class="label"><strong>Start Date:&nbsp;</strong></span><?= date('d M Y', strtotime($loan['loan_start_date'])); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Loan Amount:&nbsp;</strong></span>RWF <?= money($loan['loan_amount']); ?></td>
    <td><span class="label"><strong>Maturity Date:&nbsp;</strong></span><?= date('d M Y', strtotime($loan['maturity_date'])); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Interest Rate:&nbsp;</strong></span><?= $h($loan['interest_rate']); ?>% / year</td>
    <td><span class="label"><strong>Repayment:&nbsp;</strong></span><?= (int) $loan['repayment_period']; ?> &times; <?= $h($loan['repayment_frequency']); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Installment Amount:&nbsp;</strong></span>RWF <?= money($loan['installment_amount']); ?></td>
    <td><span class="label"><strong>Total Interest:&nbsp;</strong></span>RWF <?= money($loan['total_interest']); ?></td>
  </tr>
  <tr>
    <td><span class="label"><strong>Total Payable:&nbsp;</strong></span>RWF <?= money($loan['total_payable']); ?></td>
    <td><span class="label"><strong>Total Paid:&nbsp;</strong></span>RWF <?= money($loan['total_paid']); ?></td>
  </tr>
</table>

<?php
$sumPrincipal = $sumInterest = $sumDue = $sumPaid = 0;
$principalBalance = (float) $loan['loan_amount'];
$statusColor = ['Paid' => '#0FA968', 'Partial' => '#E68A1C'];
?>
<table class="items">
  <thead>
    <tr>
      <td>#</td>
      <td>Due Date</td>
      <td class="amount">Principal</td>
      <td class="amount">Interest</td>
      <td class="amount">Amount Due</td>
      <td class="amount">Paid</td>
      <td class="amount">Principal Balance</td>
      <td>Status</td>
    </tr>
  </thead>
  <tbody>
    <?php while ($row = mysqli_fetch_assoc($scheduleResult)) {
        $sumPrincipal += (float) $row['principal_due'];
        $sumInterest += (float) $row['interest_due'];
        $sumDue += (float) $row['amount_due'];
        $sumPaid += (float) $row['paid_amount'];
        $principalBalance = max(0, round($principalBalance - (float) $row['principal_due'], 2));
        $color = $statusColor[$row['status']] ?? '#8A90A3';
    ?>
    <tr>
      <td><?= (int) $row['installment_no']; ?></td>
      <td><?= date('d M Y', strtotime($row['due_date'])); ?></td>
      <td class="amount"><?= money($row['principal_due']); ?></td>
      <td class="amount"><?= money($row['interest_due']); ?></td>
      <td class="amount"><?= money($row['amount_due']); ?></td>
      <td class="amount"><?= money($row['paid_amount']); ?></td>
      <td class="amount"><?= money($principalBalance); ?></td>
      <td><span style="font-weight:700; color:<?= $color; ?>;"><?= $h($row['status']); ?></span></td>
    </tr>
    <?php } ?>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">Total</td>
      <td class="amount"><?= money($sumPrincipal); ?></td>
      <td class="amount"><?= money($sumInterest); ?></td>
      <td class="amount"><?= money($sumDue); ?></td>
      <td class="amount"><?= money($sumPaid); ?></td>
      <td colspan="2"></td>
    </tr>
  </tfoot>
</table>

<table class="totals">
  <tr><td>Total Paid So Far</td><td class="val">RWF <?= money($loan['total_paid']); ?></td></tr>
  <tr class="grand"><td>Outstanding Balance</td><td class="val">RWF <?= money($loan['outstanding_balance']); ?></td></tr>
</table>

<div class="sig-block">
  <div class="sig-heading"><strong>For RISE MOTIVE</strong></div>
  <div class="sig-sub">Loan Recorded By:</div>
  <div><span class="sig-label">Name:</span> <strong><?= $h($loan['created_by_name'] ?? '—'); ?></strong></div>
  <div><span class="sig-label">Position:</span> <strong><?= $h($loan['created_by_position'] ?? ucfirst($loan['created_by_role'] ?? '—')); ?></strong></div>
  <div><span class="sig-label">Contact:</span> <strong><?= $h($loan['created_by_phone'] ?? '—'); ?></strong></div>
</div>

<div class="footnote">
  This schedule shows the repayment plan for the loan from <?= $h($loan['lender']); ?>, with payments recorded up to <?= date('d M Y'); ?>. Rise Beyond Limits!
</div>
<?php
$bodyHtml = ob_get_clean();

// ---- Build the PDF ----
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 55,
    'margin_bottom' => 18,
    'margin_header' => 10,
    'margin_footer' => 6,
    'margin_left' => 15,
    'margin_right' => 15,
]);

$mpdf->SetHTMLHeader($headerHtml);
$mpdf->SetHTMLFooter($footerHtml);
$mpdf->WriteHTML($bodyHtml);

$filename = 'Loan-Schedule-LN' . str_pad($loan['id'], 6, '0', STR_PAD_LEFT) . '.pdf';

$mpdf->Output($filename, \Mpdf\Output\Destination::INLINE);