<?php
/**
 * Shared helpers for the RM Mart & Spark sales module.
 */

// NEW: needed for automatic fund allocation and reversal.
// IMPORTANT: every other page that loads these two files must use require_once
// (not plain require), otherwise PHP stops with "Cannot redeclare ...".
require_once __DIR__ . '/profit_rules.php';
require_once __DIR__ . '/fund_helpers.php';

const LOYALTY_CREDIT_THRESHOLD = 500;   // points needed for automatic Credit approval
const LOYALTY_POINTS_PER_RWF = 50;      // RWF 50 profit = 1 Loyalty Point
const SERVICE_PROFIT_MARGIN = 0.8;      // Service profit = 80% of amount paid

function sales_compute_status($amountPaid, $totalAmount) {
    if ($amountPaid >= $totalAmount - 0.01) {
        return 'Paid';
    }
    if ($amountPaid <= 0.009) {
        return 'Credit';
    }
    return 'Partially Paid';
}

/**
 * Whether a customer with this many Loyalty Points may take a Credit sale
 * automatically. 500+ points = Allowed; below that = Not Allowed (requires
 * Manager/Admin approval — see approve_discount.php).
 */
function customer_credit_status($loyaltyPoints) {
    return (int) $loyaltyPoints >= LOYALTY_CREDIT_THRESHOLD ? 'Allowed' : 'Not Allowed';
}

/**
 * Profit generated by a sale, split by Product vs Service.
 * Product profit = (Selling Price - Buying Price) per BASE unit, times the
 * total base units sold (quantity of packs × pack_size).
 * Service profit = 80% of the amount paid for the service.
 */
function calculate_sale_profit($conn, $saleId) {
    // CHANGED: uses the company profit rules (includes/profit_rules.php), so loyalty points,
    // reports and fund allocations all use the same profit. The discount is now respected.
    $lineNet  = sales_report_line_net_sql('sales', 'sale_items');
    $lineCost = sales_report_line_cost_sql('sales', 'sale_items', 'products');
    $statement = mysqli_prepare($conn, "SELECT
            COALESCE(SUM(CASE WHEN sale_items.item_type = 'Product' THEN $lineNet - $lineCost ELSE 0 END), 0) AS product_profit,
            COALESCE(SUM(CASE WHEN sale_items.item_type = 'Service' THEN $lineNet - $lineCost ELSE 0 END), 0) AS service_profit
        FROM sale_items
        JOIN sales ON sale_items.sale_id = sales.id
        LEFT JOIN products ON sale_items.product_id = products.id
        WHERE sales.id = ?");
    mysqli_stmt_bind_param($statement, 'i', $saleId);
    mysqli_stmt_execute($statement);
    $row = mysqli_fetch_assoc(mysqli_stmt_get_result($statement));

    $productProfit = round((float) $row['product_profit'], 2);
    $serviceProfit = round((float) $row['service_profit'], 2);

    return [
        'product_profit' => $productProfit,
        'service_profit' => $serviceProfit,
        'total_profit' => round($productProfit + $serviceProfit, 2),
    ];
}

/**
 * Awards Loyalty Points to a customer based on profit (RWF 50 profit = 1
 * point, rounded down). Returns the number of points actually awarded.
 * Walk-in sales (no customer) and non-positive profit award nothing.
 */
function award_loyalty_points($conn, $customerId, $profit) {
    if (!$customerId || $profit <= 0) {
        return 0;
    }

    $points = (int) floor($profit / LOYALTY_POINTS_PER_RWF);
    if ($points <= 0) {
        return 0;
    }

    $update = mysqli_prepare($conn, 'UPDATE customers SET loyalty_points = loyalty_points + ? WHERE id = ?');
    mysqli_stmt_bind_param($update, 'ii', $points, $customerId);
    mysqli_stmt_execute($update);

    return $points;
}

/**
 * NEW: removes the Loyalty Points a sale awarded (used when the sale is cancelled).
 * Never takes a customer below zero points.
 */
function revoke_loyalty_points($conn, $customerId, $points) {
    $points = (int) $points;
    if (!$customerId || $points <= 0) {
        return 0;
    }

    $update = mysqli_prepare($conn, 'UPDATE customers SET loyalty_points = GREATEST(loyalty_points - ?, 0) WHERE id = ?');
    mysqli_stmt_bind_param($update, 'ii', $points, $customerId);
    mysqli_stmt_execute($update);

    return $points;
}

/**
 * Deducts stock for every line item on a sale and posts the revenue into
 * Finance/Transactions. Called either immediately (auto-approved sale)
 * or once a Manager approves a discounted/credit-restricted sale.
 *
 * Stock is deducted in BASE units (quantity of packs sold × pack_size),
 * even though the sale itself was rung up in whatever unit (Piece, Carton,
 * Box) the cashier picked at checkout. Units themselves (Carton, Box, etc.)
 * are only ever created/managed via Add/Edit Item, not invented here.
 *
 * CHANGED: optional $userId (who triggered the finalize). When the sale ends up
 * fully Paid, its profit is allocated to the four Funds immediately.
 * Must run inside the caller's mysqli_begin_transaction().
 */
function sales_finalize($conn, $saleId, $userId = null) {
    // CHANGED: the sale row is locked (FOR UPDATE) so two finalize calls for the same sale
    // (e.g. a double click on Approve) wait for each other instead of running side by side.
    $saleStatement = mysqli_prepare($conn, 'SELECT * FROM sales WHERE id = ? FOR UPDATE');
    mysqli_stmt_bind_param($saleStatement, 'i', $saleId);
    mysqli_stmt_execute($saleStatement);
    $sale = mysqli_fetch_assoc(mysqli_stmt_get_result($saleStatement));
    if (!$sale) {
        return false;
    }

    // NEW: never finalize the same sale twice. A finalized sale already has its income
    // transaction; running again would deduct stock, record income, award points and
    // allocate profit a second time.
    if (!empty($sale['transaction_id'])) {
        return true;
    }
    if ($sale['status'] === 'Cancelled') {
        throw new RuntimeException('This sale has been cancelled and cannot be completed.');
    }

    $itemsStatement = mysqli_prepare($conn, 'SELECT * FROM sale_items WHERE sale_id = ?');
    mysqli_stmt_bind_param($itemsStatement, 'i', $saleId);
    mysqli_stmt_execute($itemsStatement);
    $items = mysqli_stmt_get_result($itemsStatement);

    $hasProduct = false;
    while ($item = mysqli_fetch_assoc($items)) {
        if ($item['item_type'] !== 'Product' || !$item['product_id']) {
            continue; // services don't touch inventory
        }
        $hasProduct = true;
        $packSize = max(1, (int) $item['pack_size']);
        $baseUnitsSold = (int) $item['quantity'] * $packSize;

        // NEW: atomic stock guard. The UPDATE only succeeds while enough stock remains, so two
        // sales at the same moment (or a late approval) can never push stock below zero.
        $update = mysqli_prepare($conn, 'UPDATE products SET quantity = quantity - ? WHERE id = ? AND quantity >= ?');
        mysqli_stmt_bind_param($update, 'iii', $baseUnitsSold, $item['product_id'], $baseUnitsSold);
        mysqli_stmt_execute($update);
        if (mysqli_stmt_affected_rows($update) !== 1) {
            throw new RuntimeException('Not enough stock to complete this sale. Please check the stock levels and try again.');
        }
    }

    // NEW: freeze the buying price (per base unit) on each product line at the moment of sale,
    // so later restocks at a different price never change this sale's cost or profit.
    // Only fills lines that have no snapshot yet, so running twice is harmless.
    $snapshot = mysqli_prepare($conn, "UPDATE sale_items
        JOIN products ON sale_items.product_id = products.id
        SET sale_items.unit_cost = products.buying_price
        WHERE sale_items.sale_id = ? AND sale_items.item_type = 'Product' AND sale_items.unit_cost IS NULL");
    mysqli_stmt_bind_param($snapshot, 'i', $saleId);
    mysqli_stmt_execute($snapshot);

    // NEW (spec section 8): the stock just left the shop, so the RM Capital Fund goes down by
    // its BUYING price (cost of stock sold). This happens for every finalized sale, paid or
    // not, because the goods leave either way. Revenue and profit are handled separately.
    $stockActor = $userId !== null ? (int) $userId : ($sale['recorded_by'] !== null ? (int) $sale['recorded_by'] : null);
    record_sale_stock_cost($conn, (int) $saleId, $stockActor);

    // A sale can mix Product and Service line items, but a transaction only
    // takes one category now — tag it Product if any physical item was sold,
    // otherwise Service.
    $category = $hasProduct ? 'Product' : 'Service';

    $description = 'Sale #' . $saleId . ' (' . $sale['payment_method'] . ')';
    $transactionStatement = mysqli_prepare($conn, "INSERT INTO transactions (category, transaction_type, amount, transaction_date, description, recorded_by, status) VALUES (?, 'Income', ?, ?, ?, ?, 'approved')");
    mysqli_stmt_bind_param($transactionStatement, 'sdssi', $category, $sale['total_amount'], $sale['sale_date'], $description, $sale['recorded_by']);
    mysqli_stmt_execute($transactionStatement);
    $transactionId = mysqli_insert_id($conn);

    // Profit + Loyalty Points: RWF 50 profit = 1 point, added to the
    // customer's balance automatically once the sale is finalized.
    $profit = calculate_sale_profit($conn, $saleId);
    $pointsEarned = award_loyalty_points($conn, $sale['customer_id'], $profit['total_profit']);

    $newStatus = sales_compute_status((float) $sale['amount_paid'], (float) $sale['total_amount']);
    $updateSale = mysqli_prepare($conn, 'UPDATE sales SET status = ?, transaction_id = ?, loyalty_points_earned = ? WHERE id = ?');
    mysqli_stmt_bind_param($updateSale, 'siii', $newStatus, $transactionId, $pointsEarned, $saleId);
    mysqli_stmt_execute($updateSale);

    // NEW (spec section 1): a fully Paid sale puts its profit into the Funds right now.
    // Credit / Partially Paid sales are allocated later, by the payment that makes them Paid
    // (the same call must be added to the code that records payments).
    if ($newStatus === 'Paid') {
        $actor = $userId !== null ? (int) $userId : ($sale['recorded_by'] !== null ? (int) $sale['recorded_by'] : null);
        allocate_sale_profit($conn, $saleId, $actor);
    }

    return true;
}
/**
 * Cancels a Credit, Partially Paid, or fully Paid sale. Deletes the linked
 * income transaction (it's being reversed) and marks the sale Cancelled.
 *
 * CHANGED: $returnToStock (default false).
 *   false = goods already left the shop: stock and the Capital Fund cost stay as they are
 *           (same behaviour as before).
 *   true  = goods came back (e.g. a wrongly entered sale): they are added back to stock
 *           and their cost is returned to the RM Capital Fund.
 * amount_paid is reset to 0 so a cancelled sale never shows a stale paid
 * balance; if cash was actually collected and needs to go back to the
 * customer, that refund must be recorded separately (e.g. as an expense).
 *
 * Already 'Cancelled' sales and sales still 'Pending Discount Approval'
 * are rejected.
 *
 * CHANGED: Loyalty Points the sale awarded are now taken back on cancellation
 * (spec section 2: reverse ALL effects of the transaction). Before, a customer
 * could collect points from sales that were later cancelled and use them to
 * reach the 500 points needed for automatic Credit approval.
 *
 * CHANGED (spec section 2): everything now happens in ONE database transaction,
 * the sale is re-checked under a lock (so a double click cannot cancel twice),
 * and every fund movement the sale created is reversed automatically.
 */
function sales_cancel($conn, $saleId, $userId, $reason, $returnToStock = false) {
    mysqli_begin_transaction($conn);

    try {
        $saleStatement = mysqli_prepare($conn, 'SELECT * FROM sales WHERE id = ? FOR UPDATE');
        mysqli_stmt_bind_param($saleStatement, 'i', $saleId);
        mysqli_stmt_execute($saleStatement);
        $sale = mysqli_fetch_assoc(mysqli_stmt_get_result($saleStatement));

        if (!$sale) {
            mysqli_rollback($conn);
            return ['ok' => false, 'error' => 'Sale not found.'];
        }
        if (!in_array($sale['status'], ['Credit', 'Partially Paid', 'Paid'], true)) {
            mysqli_rollback($conn);
            return ['ok' => false, 'error' => 'Only Credit, Partially Paid, or Paid sales can be cancelled.'];
        }

        if (!empty($sale['transaction_id'])) {
            $deleteTx = mysqli_prepare($conn, 'DELETE FROM transactions WHERE id = ?');
            mysqli_stmt_bind_param($deleteTx, 'i', $sale['transaction_id']);
            mysqli_stmt_execute($deleteTx);
        }

        // NEW: take back the Loyalty Points this sale awarded.
        revoke_loyalty_points($conn, $sale['customer_id'], $sale['loyalty_points_earned'] ?? 0);

        $updateSale = mysqli_prepare($conn, 'UPDATE sales
        SET status = "Cancelled", transaction_id = NULL, amount_paid = 0, cancelled_by = ?, cancelled_at = NOW(), cancel_reason = ?,
            cancel_requested_by = NULL, cancel_requested_at = NULL, cancel_request_reason = NULL
        WHERE id = ?');
        mysqli_stmt_bind_param($updateSale, 'isi', $userId, $reason, $saleId);
        mysqli_stmt_execute($updateSale);

        // NEW: reverse the profit allocated to the four Funds.
        // Does nothing if the sale never allocated anything.
        reverse_sale_profit($conn, (int) $saleId, $userId !== null ? (int) $userId : null);

        // NEW (spec sections 2 and 8): when the goods come back, put them back into stock
        // and return their cost to the RM Capital Fund. When they do not come back, both
        // stay as they are, so the Capital Fund keeps matching the real stock value.
        if ($returnToStock) {
            $itemsStatement = mysqli_prepare($conn, "SELECT product_id, quantity, pack_size FROM sale_items WHERE sale_id = ? AND item_type = 'Product' AND product_id IS NOT NULL");
            mysqli_stmt_bind_param($itemsStatement, 'i', $saleId);
            mysqli_stmt_execute($itemsStatement);
            $returnItems = mysqli_fetch_all(mysqli_stmt_get_result($itemsStatement), MYSQLI_ASSOC);

            $restock = mysqli_prepare($conn, 'UPDATE products SET quantity = quantity + ? WHERE id = ?');
            foreach ($returnItems as $item) {
                $baseUnits = (int) $item['quantity'] * max(1, (int) $item['pack_size']);
                $productId = (int) $item['product_id'];
                mysqli_stmt_bind_param($restock, 'ii', $baseUnits, $productId);
                mysqli_stmt_execute($restock);
            }

            reverse_sale_stock_cost($conn, (int) $saleId, $userId !== null ? (int) $userId : null);
        }

        mysqli_commit($conn);
        return ['ok' => true];
    } catch (Throwable $e) {
        mysqli_rollback($conn);
        error_log('sales_cancel failed for sale #' . $saleId . ': ' . $e->getMessage());
        return ['ok' => false, 'error' => 'Unable to cancel the sale. Nothing was changed.'];
    }
}
/**
 * Employee flags a Credit/Partially Paid/Paid sale for cancellation. Nothing is
 * actually cancelled yet — an Admin/Manager must approve it.
 */
function sales_request_cancel($conn, $saleId, $userId, $reason) {
    $saleStatement = mysqli_prepare($conn, 'SELECT * FROM sales WHERE id = ?');
    mysqli_stmt_bind_param($saleStatement, 'i', $saleId);
    mysqli_stmt_execute($saleStatement);
    $sale = mysqli_fetch_assoc(mysqli_stmt_get_result($saleStatement));

    if (!$sale) {
        return ['ok' => false, 'error' => 'Sale not found.'];
    }
    if (!in_array($sale['status'], ['Credit', 'Partially Paid', 'Paid'], true)) {
        return ['ok' => false, 'error' => 'Only Credit, Partially Paid, or Paid sales can be requested for cancellation.'];
    }
    if (!empty($sale['cancel_requested_by'])) {
        return ['ok' => false, 'error' => 'A cancellation request is already pending for this sale.'];
    }

    $update = mysqli_prepare($conn, 'UPDATE sales SET cancel_requested_by = ?, cancel_requested_at = NOW(), cancel_request_reason = ? WHERE id = ?');
    mysqli_stmt_bind_param($update, 'isi', $userId, $reason, $saleId);
    mysqli_stmt_execute($update);

    return ['ok' => true];
}

/**
 * Admin/Manager rejects a pending cancellation request — the sale is left
 * exactly as it was, just clears the request flags.
 */
function sales_reject_cancel_request($conn, $saleId) {
    $update = mysqli_prepare($conn, 'UPDATE sales SET cancel_requested_by = NULL, cancel_requested_at = NULL, cancel_request_reason = NULL WHERE id = ?');
    mysqli_stmt_bind_param($update, 'i', $saleId);
    mysqli_stmt_execute($update);
    return ['ok' => true];
}