<?php
require '../../config/db.php';
require '../../includes/business_party_helpers.php';
require '../../vendor/autoload.php'; // adjust path if your vendor folder is elsewhere

use Mpdf\Mpdf;

$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
if (!$id) { header('Location: index.php?error=Invalid purchase order requested.'); exit; }

$statement = mysqli_prepare($conn, 'SELECT purchase_orders.*, created.names AS created_by_name, created.role AS created_by_role, created.phone AS created_by_phone
    FROM purchase_orders
    LEFT JOIN users created ON purchase_orders.created_by = created.id
    WHERE purchase_orders.id = ?');
mysqli_stmt_bind_param($statement, 'i', $id);
mysqli_stmt_execute($statement);
$po = mysqli_fetch_assoc(mysqli_stmt_get_result($statement));
if (!$po) { header('Location: index.php?error=Purchase order not found.'); exit; }

$supplierParty = business_party_by_id($conn, $po['supplier_party_id']);

$itemsStatement = mysqli_prepare($conn, 'SELECT purchase_order_items.*, products.product_name, products.product_code, products.unit
    FROM purchase_order_items LEFT JOIN products ON purchase_order_items.product_id = products.id
    WHERE purchase_order_id = ? ORDER BY purchase_order_items.id');
mysqli_stmt_bind_param($itemsStatement, 'i', $id);
mysqli_stmt_execute($itemsStatement);
$items = mysqli_stmt_get_result($itemsStatement);

$isDraft = $po['status'] === 'Draft';
$isCancelled = $po['status'] === 'Cancelled';
$isReceived = $po['status'] === 'Received';

function money($v) { return number_format((float) $v, 2); }

$docTitle = 'Purchase Order';
$docNumber = 'No. PO-' . str_pad($po['id'], 6, '0', STR_PAD_LEFT);
$statusLabel = htmlspecialchars($po['status'], ENT_QUOTES, 'UTF-8');
$statusColor = $isDraft ? '#B8860B' : ($isCancelled ? '#8A90A3' : ($isReceived ? '#0FA968' : '#1E2FE0'));
$statusBg    = $isDraft ? '#FDF3E3' : ($isCancelled ? '#F1F3F9' : ($isReceived ? '#E1F7EE' : '#E8EBFC'));

$logoPath = __DIR__ . '/../../assets/images/logo.jpg';

// ---- Repeating header ----
$headerHtml = '
<table width="100%" style="border-bottom:2px solid #1E2333; padding-bottom:6px;">
  <tr>
    <td style="width:60%; vertical-align:top;">
      <img src="' . $logoPath . '" style="height:46px; width:auto; display:block; margin-bottom:5px;">
      <span style="font-size:16px; font-weight:800; color:#1E2333;">RISE MOTIVE</span><br>
      <span style="font-size:8px; color:#8A90A3;">TIN Number:122923513</span><br>
      <span style="font-size:8px; color:#8A90A3;">website: www.risemotive.rw</span><br>
      <span style="font-size:9px; font-weight:700; color:#1E2333; margin-top:2px; display:inline-block;">Kicukiro District, Kigali, Rwanda</span>
    </td>
    <td style="width:40%; text-align:right; vertical-align:top;">
      <span style="font-size:14px; font-weight:700; color:#1E2333;">' . htmlspecialchars($docTitle, ENT_QUOTES, 'UTF-8') . '</span><br>
      <span style="font-size:9px; color:#8A90A3;">' . htmlspecialchars($docNumber, ENT_QUOTES, 'UTF-8') . '</span><br>
      <span style="font-size:8px; font-weight:700; color:' . $statusColor . '; background:' . $statusBg . '; padding:2px 8px; border-radius:8px;">' . $statusLabel . '</span>
    </td>
  </tr>
</table>';

// ---- Repeating footer ----
$footerHtml = '
<table width="100%" style="border-top:1px solid #E4E8F2; padding-top:4px;">
  <tr>
    <td style="width:50%; font-size:8px; color:#8A90A3;">Generated by MY MOTIVE &middot; ' . date('d M Y, H:i') . '</td>
    <td style="width:50%; text-align:right; font-size:8px; color:#8A90A3;">Page {PAGENO} of {nbpg}</td>
  </tr>
</table>';

// ---- Main body content ----
ob_start();
?>
<style>
  body { font-family: sans-serif; color:#1E2333; font-size:11px; }
  .watermark-wrap { text-align:center; margin: -10px 0 6px; }
  .watermark-text { color:#E24B4A; font-size:26px; font-weight:800; opacity:0.35; }
  table.info-grid { width:100%; border:1px solid #E4E8F2; border-radius:6px; font-size:10px; margin-bottom:14px; }
  table.info-grid td { padding:5px 10px; }
  table.info-grid .label { color:#8A90A3; width:110px; display:inline-block; }
  table.items { width:100%; border-collapse:collapse; font-size:10px; margin-bottom:10px; }
  table.items thead td { font-size:9px; text-transform:uppercase; color:#8A90A3; border-bottom:1px solid #E4E8F2; padding:4px 0; font-weight:700; }
  table.items tbody td { padding:5px 0; border-bottom:1px solid #E4E8F2; }
  table.items td.amount { text-align:right; }
  table.totals { width:45%; margin-left:55%; font-size:10px; }
  table.totals td { padding:3px 0; }
  table.totals td.val { text-align:right; }
  table.totals tr.grand td { border-top:2px solid #1E2333; font-size:13px; font-weight:800; color:#1E2FE0; padding-top:6px; }
  .sig-block { margin-top:18px; padding-top:10px; border-top:1px solid #E4E8F2; font-size:10px; }
  .sig-heading { font-weight:700; }
  .sig-sub { color:#8A90A3; font-weight:600; margin-bottom:6px; }
  .sig-label { color:#8A90A3; display:inline-block; width:70px; }
  .footnote { margin-top:12px; font-size:9px; color:#8A90A3; }
</style>

<?php if ($isDraft) { ?>
  <div class="watermark-wrap"><span class="watermark-text">DRAFT</span></div>
<?php } elseif ($isCancelled) { ?>
  <div class="watermark-wrap"><span class="watermark-text">CANCELLED</span></div>
<?php } ?>

<table class="info-grid">
  <tr>
    <td width="50%"><span class="label">Supplier:</span><?= htmlspecialchars($po['supplier'] ?: '—', ENT_QUOTES, 'UTF-8'); ?></td>
    <td width="50%"><span class="label">Order Date:</span><?= date('d M Y', strtotime($po['order_date'])); ?></td>
  </tr>
  <?php if ($supplierParty) { ?>
  <tr>
    <td><span class="label">TIN:</span><?= htmlspecialchars($supplierParty['tin'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
    <td><span class="label">Expected Delivery:</span><?= $po['expected_delivery_date'] ? date('d M Y', strtotime($po['expected_delivery_date'])) : '—'; ?></td>
  </tr>
  <tr>
    <td><span class="label">Representative:</span><?= htmlspecialchars($supplierParty['representative_name'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
    <td><span class="label">Prepared By:</span><?= htmlspecialchars($po['created_by_name'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
  </tr>
  <tr>
    <td><span class="label">Phone:</span><?= htmlspecialchars($supplierParty['phone'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
    <td><span class="label">Email:</span><?= htmlspecialchars($supplierParty['email'] ?: '—', ENT_QUOTES, 'UTF-8'); ?></td>
  </tr>
  <?php } else { ?>
  <tr>
    <td><span class="label">Prepared By:</span><?= htmlspecialchars($po['created_by_name'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
    <td></td>
  </tr>
  <?php } ?>
</table>

<table class="items">
  <thead>
    <tr><td>Product</td><td>Code</td><td>Bought As</td><td class="amount">Total Units</td><td class="amount">Cost / Unit</td><td class="amount">Line Total</td></tr>
  </thead>
  <tbody>
    <?php while ($item = mysqli_fetch_assoc($items)) {
        $packSize = max(1, (int) $item['pack_size']);
        $totalUnits = (int) $item['quantity'] * $packSize;
    ?>
    <tr>
      <td><?= htmlspecialchars($item['product_name'] ?? 'Deleted product', ENT_QUOTES, 'UTF-8'); ?></td>
      <td><?= htmlspecialchars($item['product_code'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></td>
      <td>
        <?= (int) $item['quantity']; ?> x <?= htmlspecialchars($item['pack_label'], ENT_QUOTES, 'UTF-8'); ?>
        <?php if ($packSize > 1) { ?>
          <br><span style="font-size:9px; color:#8A90A3;">(<?= $packSize; ?> each)</span>
        <?php } ?>
      </td>
      <td class="amount"><?= $totalUnits; ?> <?= htmlspecialchars($item['unit'] ?? '', ENT_QUOTES, 'UTF-8'); ?></td>
      <td class="amount"><?= money($item['unit_cost']); ?></td>
      <td class="amount"><?= money($item['line_total']); ?></td>
    </tr>
    <?php } ?>
  </tbody>
</table>

<table class="totals">
  <tr class="grand"><td>Total</td><td class="val">RWF <?= money($po['total_amount']); ?></td></tr>
</table>

<?php if ($po['notes']) { ?>
<div style="margin-top:10px; font-size:10px;">
  <strong>Notes:</strong> <?= nl2br(htmlspecialchars($po['notes'], ENT_QUOTES, 'UTF-8')); ?>
</div>
<?php } ?>

<?php if (!$isCancelled) { ?>
<div class="sig-block">
  <div class="sig-heading">For RISE MOTIVE</div>
  <div class="sig-sub">Purchase Order Prepared By:</div>
  <div><span class="sig-label">Name:</span> <strong><?= htmlspecialchars($po['created_by_name'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></strong></div>
  <div><span class="sig-label">Position:</span> <strong><?= htmlspecialchars(ucfirst($po['created_by_role'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></strong></div>
  <div><span class="sig-label">Contact:</span> <strong><?= htmlspecialchars($po['created_by_phone'] ?? '—', ENT_QUOTES, 'UTF-8'); ?></strong></div>
</div>
<?php } ?>

<div class="footnote">
  <?php if ($isDraft) { ?>
    This Purchase Order is still a draft and has not been sent to the supplier yet.
  <?php } elseif ($isCancelled) { ?>
    This Purchase Order was cancelled and was not applied to inventory or finance records.
  <?php } elseif ($isReceived) { ?>
    This order has been received in full — stock and finance records were updated automatically.
  <?php } else { ?>
    Please confirm receipt and expected delivery date with the supplier.
  <?php } ?>
</div>
<?php
$bodyHtml = ob_get_clean();

// ---- Build the PDF ----
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 50,
    'margin_bottom' => 18,
    'margin_header' => 10,
    'margin_footer' => 6,
    'margin_left' => 15,
    'margin_right' => 15,
]);

$mpdf->SetHTMLHeader($headerHtml);
$mpdf->SetHTMLFooter($footerHtml);
$mpdf->WriteHTML($bodyHtml);

$filename = ($isDraft ? 'Draft-PO' : ($isCancelled ? 'Cancelled-PO' : 'Purchase-Order'))
    . '-RM' . str_pad($po['id'], 6, '0', STR_PAD_LEFT) . '.pdf';

$mpdf->Output($filename, \Mpdf\Output\Destination::INLINE);